language: node_js
node_js:
- "8"
install:
  - sudo apt-get update
  - cd hashstore/bakery/js
  - npm install
  - cd ../../..
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n py4 python=3.4
  - conda create -q -n py5 python=3.5
  - conda create -q -n py6 python=3.6
  - for e in py4 py5 py6  ;
    do
      source activate $e;
      pip install -r requirements.txt;
      pip install -r test-requirements.txt;
    done

script:
  - cd hashstore/bakery/js
  - npm run build
  - cd ../../..
  - for e in py4 py5 py6 ;
    do
      source activate $e;
      coverage run -p -m nose;
      echo $? > $e.status;
    done
  - source activate py4
  - coverage combine
  - coverage report -m
  - codecov
  - rm .coverage
  - test $(cat py4.status) == 0 && test $(cat py5.status) == 0 && test $(cat py6.status) == 0
