language: node_js
node_js:
- "8"
install:
  - sudo apt-get update
  - cd hashstore/bakery/js
  - npm install
  - cd ../../..
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - for e in 6;
    do
      conda create -q -n py$e python=3.$e;
      source activate py$e;
      pip install -r requirements.txt;
      pip install -r test-requirements.txt;
    done

script:
  - cd hashstore/bakery/js
  - npm run build
  - cd ../../..
  - for e in 6;
    do
      source activate py$e;
      coverage run -p -m nose;
      echo $? > py$e.status;
    done
  - source activate py6
  - coverage combine
  - coverage report -m
  - codecov
  - rm .coverage
  - test $(cat py6.status) == 0
