
trigger:
- master

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - name: requirements
        script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: test
        script: python scent.py current
      - name: sdist
        script: python setup.py sdist
      - name: list_dist
        script: dir dist
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: 'dist'
          artifactName: 'hashstore-win.tgz'
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - name: requirements
        script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: test
        script: python scent.py current
      - name: sdist
        script: python setup.py sdist
      - name: list_dist
        script: ls -l dist
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: 'dist'
          artifactName: 'hashstore-linux.tgz'
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - name: requirements
        script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: test
        script: python scent.py current
      - name: sdist
        script: python setup.py sdist
      - name: list_dist
        script: ls -l dist
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: 'dist'
          artifactName: 'hashstore-macos.tgz'
