trigger:
  - master

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        name: requirements
      - script: python setup.py sdist
        name: sdist
      - script: dir dist
      - script: python scent.py current
        name: test
      - task: PublishPipelineArtifact@0
        name: publish_cov
        inputs:
          targetPath: coverage_html_report
          artifactName: coverage_win
      - task: PublishPipelineArtifact@0
        name: publish_dist
        inputs:
          targetPath: dist
          artifactName: hashstore-win.tgz
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        name: requirements
      - script: python setup.py sdist
        name: sdist
      - script: ls -l dist
      - script: python scent.py current
        name: test
      - task: PublishPipelineArtifact@0
        name: publish_cov
        inputs:
          targetPath: coverage_html_report
          artifactName: coverage_linux
      - task: PublishPipelineArtifact@0
        name: publish_dist
        inputs:
          targetPath: dist
          artifactName: hashstore-linux.tgz
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        name: requirements
      - script: python setup.py sdist
        name: sdist
      - script: ls -l dist
        condition: always()
      - script: python scent.py current
        name: test
      - script: find . -ls
        condition: always()
      - task: PublishPipelineArtifact@0
        name: publish_cov
        inputs:
          targetPath: coverage_html_report
          artifactName: coverage_macos
      - task: PublishPipelineArtifact@0
        name: publish_dist
        inputs:
          targetPath: dist
          artifactName: hashstore-macos.tgz
  - job: Release
    dependsOn:
      - Windows
      - macOS
      - Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: ls -l
      - script: cat version.txt
      - script: python setup.py release
