
trigger:
- master

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        name: requirements
      - script: python setup.py sdist
        name: sdist
      - script: python scent.py current
        name: test
      - script: dir dist
      - task: PublishPipelineArtifact@0
        name: publish_test_out
        conditions: or(failed(), canceled())
        inputs:
          targetPath: 'test-out'
          artifactName: 'test-out-win'
      - task: PublishPipelineArtifact@0
        name: publish_dist
        inputs:
          targetPath: 'dist'
          artifactName: 'hashstore-win.tgz'
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        name: requirements
      - script: python setup.py sdist
        name: sdist
      - script: python scent.py current
        name: test
      - script: ls -l dist
      - task: PublishPipelineArtifact@0
        name: publish_test_out
        conditions: or(failed(), canceled())
        inputs:
          targetPath: 'test-out'
          artifactName: 'test-out-linux'
      - task: PublishPipelineArtifact@0
        name: publish_dist
        inputs:
          targetPath: 'dist'
          artifactName: 'hashstore-linux.tgz'
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          python -V
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        name: requirements
      - script: python setup.py sdist
        name: sdist
      - script: python scent.py current
        name: test
      - script: ls -l dist
      - task: PublishPipelineArtifact@0
        name: publish_test_out
        conditions: or(failed(), canceled())
        inputs:
          targetPath: 'test-out'
          artifactName: 'test-out-macos'
      - task: PublishPipelineArtifact@0
        name: publish_dist
        inputs:
          targetPath: 'dist'
          artifactName: 'hashstore-macos.tgz'
